# CPSC 368 – Group 4: YouTube Data Collection
## Phase 3 – Data Collection from MIT datasets

This notebook collects MIT data and refines into CSV files that can then be uploaded to SQL Oracle

In [57]:
import pandas as pd
import os

In [58]:
df_1976_2020 = pd.read_csv('../../source_data/mit/1976-2020-president.csv')
df_2024 = pd.read_csv('../../source_data/mit/2024-president-state.csv')

df_2016 = df_1976_2020[df_1976_2020['year'] == 2016].reset_index(drop=True)
df_2020 = df_1976_2020[df_1976_2020['year'] == 2020].reset_index(drop=True)

print("2016:")
print(df_2016.shape[0], "rows")
display(df_2016.head())
print("2020:")
print(df_2020.shape[0], "rows")
display(df_2020.head())
print("2024:")
print(df_2024.shape[0], "rows")
display(df_2024.head())

2016:
345 rows

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
0,2016,ALABAMA,AL,1,63,41,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,1318255,2123372,20210113,NaN,REPUBLICAN
1,2016,ALABAMA,AL,1,63,41,US PRESIDENT,"CLINTON, HILLARY",DEMOCRAT,False,729547,2123372,20210113,NaN,DEMOCRAT
2,2016,ALABAMA,AL,1,63,41,US PRESIDENT,"JOHNSON, GARY",LIBERTARIAN,False,44467,2123372,20210113,NaN,LIBERTARIAN
3,2016,ALABAMA,AL,1,63,41,US PRESIDENT,NaN,NaN,True,21712,2123372,20210113,NaN,OTHER
4,2016,ALABAMA,AL,1,63,41,US PRESIDENT,"STEIN, JILL",GREEN,False,9391,2123372,20210113,NaN,OTHER

2020:
547 rows

,year,state,state_po,state_fips,state_cen,state_ic,office,candidate,party_detailed,writein,candidatevotes,totalvotes,version,notes,party_simplified
0,2020,ALABAMA,AL,1,63,41,US PRESIDENT,"BIDEN, JOSEPH R. JR",DEMOCRAT,False,849624,2323282,20210113,NaN,DEMOCRAT
1,2020,ALABAMA,AL,1,63,41,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,1441170,2323282,20210113,NaN,REPUBLICAN
2,2020,ALABAMA,AL,1,63,41,US PRESIDENT,"JORGENSEN, JO",LIBERTARIAN,False,25176,2323282,20210113,NaN,LIBERTARIAN
3,2020,ALABAMA,AL,1,63,41,US PRESIDENT,NaN,NaN,True,7312,2323282,20210113,NaN,OTHER
4,2020,ALASKA,AK,2,94,81,US PRESIDENT,"BIDEN, JOSEPH R. JR",DEMOCRAT,False,153778,359530,20210113,NaN,DEMOCRAT

2024:
535 rows

,year,state,state_po,state_fips,state_ic,office,candidate,party_detailed,party_simplified,writein,mode,votes,totalvotes,stage,special,unofficial,version
0,2024,ALASKA,AK,2,81.0,US PRESIDENT,"HARRIS, KAMALA D.",DEMOCRAT,DEMOCRAT,False,TOTAL,140026,338177,GEN,False,False,2025-11-20
1,2024,ALASKA,AK,2,81.0,US PRESIDENT,"KENNEDY, ROBERT F. JR",NON-AFFILIATED,OTHER,False,TOTAL,5670,338177,GEN,False,False,2025-11-20
2,2024,ALASKA,AK,2,81.0,US PRESIDENT,"OLIVER, CHASE",LIBERTARIAN,LIBERTARIAN,False,TOTAL,3040,338177,GEN,False,False,2025-11-20
3,2024,ALASKA,AK,2,81.0,US PRESIDENT,"SONSKI, PETER",AMERICAN SOLIDARITY,OTHER,False,TOTAL,702,338177,GEN,False,False,2025-11-20
4,2024,ALASKA,AK,2,81.0,US PRESIDENT,"STEIN, JILL",NON-AFFILIATED,OTHER,False,TOTAL,2342,338177,GEN,False,False,2025-11-20

In [59]:
common_cols = df_2016.columns.intersection(df_2020.columns).intersection(df_2024.columns)
print('Common columns:', list(common_cols))

df = pd.concat([df_2016, df_2020, df_2024], ignore_index=True)[common_cols]
print(df.shape[0], "rows total amongst 2016, 2020, and 2024 datasets")
display(df.head())
display(df['year'].unique())

# Removing all parties except DEM and REP, and all rows with missing values in the 'candidate' column
df = df[df['party_simplified'].isin(['DEMOCRAT', 'REPUBLICAN'])]
df = df.dropna(subset=['candidate'])
print(df.shape[0], "rows after filtering for DEM and REP parties and dropping rows with missing candidate names")
display(df.head())

Common columns: ['year', 'state', 'state_po', 'state_fips', 'state_ic', 'office', 'candidate', 'party_detailed', 'writein', 'totalvotes', 'version', 'party_simplified']
1427 rows total amongst 2016, 2020, and 2024 datasets

,year,state,state_po,state_fips,state_ic,office,candidate,party_detailed,writein,totalvotes,version,party_simplified
0,2016,ALABAMA,AL,1,41.0,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,2123372,20210113,REPUBLICAN
1,2016,ALABAMA,AL,1,41.0,US PRESIDENT,"CLINTON, HILLARY",DEMOCRAT,False,2123372,20210113,DEMOCRAT
2,2016,ALABAMA,AL,1,41.0,US PRESIDENT,"JOHNSON, GARY",LIBERTARIAN,False,2123372,20210113,LIBERTARIAN
3,2016,ALABAMA,AL,1,41.0,US PRESIDENT,NaN,NaN,True,2123372,20210113,OTHER
4,2016,ALABAMA,AL,1,41.0,US PRESIDENT,"STEIN, JILL",GREEN,False,2123372,20210113,OTHER

array([2016, 2020, 2024])

308 rows after filtering for DEM and REP parties and dropping rows with missing candidate names

,year,state,state_po,state_fips,state_ic,office,candidate,party_detailed,writein,totalvotes,version,party_simplified
0,2016,ALABAMA,AL,1,41.0,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,2123372,20210113,REPUBLICAN
1,2016,ALABAMA,AL,1,41.0,US PRESIDENT,"CLINTON, HILLARY",DEMOCRAT,False,2123372,20210113,DEMOCRAT
5,2016,ALASKA,AK,2,81.0,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,318608,20210113,REPUBLICAN
6,2016,ALASKA,AK,2,81.0,US PRESIDENT,"CLINTON, HILLARY",DEMOCRAT,False,318608,20210113,DEMOCRAT
12,2016,ARIZONA,AZ,4,61.0,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,2573165,20210113,REPUBLICAN

### Data Quality Testing

In [60]:
assert(df['office'].nunique() == 1 and df['office'].unique()[0] == 'US PRESIDENT')
assert(df['state'].nunique() == 51)

### Upload

In [61]:
os.makedirs('../../cleaned_data/mit', exist_ok=True)    
display(df.head())
df.rename(columns={'party_simplified': 'party', 'totalvotes': 'votes'}, inplace=True)
final_df = df[['year', 'state', 'state_po', 'candidate', 'party', 'votes']]
display(final_df.head())
final_df.to_csv('../../cleaned_data/mit/mit_presidential_election_data.csv', index=False)

,year,state,state_po,state_fips,state_ic,office,candidate,party_detailed,writein,totalvotes,version,party_simplified
0,2016,ALABAMA,AL,1,41.0,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,2123372,20210113,REPUBLICAN
1,2016,ALABAMA,AL,1,41.0,US PRESIDENT,"CLINTON, HILLARY",DEMOCRAT,False,2123372,20210113,DEMOCRAT
5,2016,ALASKA,AK,2,81.0,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,318608,20210113,REPUBLICAN
6,2016,ALASKA,AK,2,81.0,US PRESIDENT,"CLINTON, HILLARY",DEMOCRAT,False,318608,20210113,DEMOCRAT
12,2016,ARIZONA,AZ,4,61.0,US PRESIDENT,"TRUMP, DONALD J.",REPUBLICAN,False,2573165,20210113,REPUBLICAN

    year    state state_po         candidate       party    votes
0   2016  ALABAMA       AL  TRUMP, DONALD J.  REPUBLICAN  2123372
1   2016  ALABAMA       AL  CLINTON, HILLARY    DEMOCRAT  2123372
5   2016   ALASKA       AK  TRUMP, DONALD J.  REPUBLICAN   318608
6   2016   ALASKA       AK  CLINTON, HILLARY    DEMOCRAT   318608
12  2016  ARIZONA       AZ  TRUMP, DONALD J.  REPUBLICAN  2573165